### ISSUE TITLE
Some new potential nodes for the flows.

### ISSUE THREAD

**Issue by dkikalis** [thesheehans/airtouch2p-nodered-mqtt#3]
Here is a couple of flows that I found useful  It uses the Home Assistant nodes to add the sensor.  I have an issue sending the unit anything that sets parameters.

[{"id":"d83ac1da380d21ff","type":"debug","z":"58b5e101.08975","name":"debug 28","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":780,"y":500,"wires":[]},{"id":"6c8b754df2e94509","type":"inject","z":"58b5e101.08975","name":"GET AC STATUS","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[85,85,128,176,1,192,0,8,35,0,0,0,0,0,0,0,125,176]","payloadType":"bin","x":160,"y":440,"wires":[["1447f9371f8c82c5"]]},{"id":"1447f9371f8c82c5","type":"tcp request","z":"58b5e101.08975","name":"","server":"IUP ADDRESS","port":"9200","out":"time","ret":"buffer","splitc":"0","newline":"","trim":false,"tls":"","x":190,"y":500,"wires":[["8de6264fab2dcb60"]]},{"id":"8de6264fab2dcb60","type":"function","z":"58b5e101.08975","name":"AC State","func":"msg.AC = []\nmsg.AC.Count = (msg.payload.length - 16-2)/10\nfor (let i = 0; i < msg.AC.Count; i++) {\n  msg.AC[i] = {}\n  msg.AC[i].UnitNumber = i+1\nswitch(msg.payload[16 + (i * 10)] & 240) {\n  case 0:\n    msg.AC[i].Status = 0\n    break;\n  case 16:\n    msg.AC[i].Status = 1\n    break;\n  case 32:\n    msg.AC[i].Status = \"Away(Off)\"\n    break;\n  case 48:\n    msg.AC[i].Status = \"Away(On)\"\n    break;\n  case 80:\n    msg.AC[i].Status = \"Sleep\"\n    break;\n}\nswitch(msg.payload[17 + (i * 10)] & 240) {\n  case 0:\n    msg.AC[i].Mode = \"Auto\"\n    break;\n  case 16:\n    msg.AC[i].Mode = \"Heat\"\n    break;\n  case 32:\n    msg.AC[i].Mode = \"Dry\"\n    break;\n  case 48:\n    msg.AC[i].Mode = \"Fan\"\n    break;\n  case 64:\n    msg.AC[i].Mode = \"Cool\"\n    break;\n  case 128:\n    msg.AC[i].Mode = \"Auto Heat\"\n    break;\n  case 144:\n    msg.AC[i].Mode = \"Auto Cool\"\n    break;\n}\nswitch(msg.payload[17 + (i * 10)] & 15) {\n  case 0:\n    msg.AC[i].FanSpeed = \"Auto\"\n    break;\n  case 1:\n    msg.AC[i].FanSpeed = \"Quiet\"\n    break;\n  case 2:\n    msg.AC[i].FanSpeed = \"Low\"\n    break;\n  case 3:\n    msg.AC[i].FanSpeed = \"Medium\"\n    break;\n  case 4:\n    msg.AC[i].FanSpeed = \"High\"\n    break;\n  case 5:\n    msg.AC[i].FanSpeed = \"Powerful\"\n    break;\n  case 6:\n    msg.AC[i].FanSpeed = \"Turbo\"\n    break;\n}\n\nmsg.AC[i].SetPoint = (msg.payload[18 + (i * 10)] +100)/10\nmsg.AC[i].Temp = (msg.payload[20 + (i * 10)]*256 + msg.payload[21 + (i * 10)] -500)/10\n}\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":400,"y":500,"wires":[["dd5d3c999050923b"]]},{"id":"cdca0a148cb66d6f","type":"inject","z":"58b5e101.08975","name":"GET Group STATUS","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[85,85,128,176,1,192,0,8,33,0,0,0,0,0,0,0,164,49]","payloadType":"bin","x":150,"y":560,"wires":[["8637643ed74242fa"]]},{"id":"8637643ed74242fa","type":"tcp request","z":"58b5e101.08975","name":"","server":"TP ADDRESS","port":"9200","out":"time","ret":"buffer","splitc":"100","newline":"","trim":false,"tls":"","x":370,"y":560,"wires":[["e901f0db6881d4b9"]]},{"id":"9c93168910c197ea","type":"debug","z":"58b5e101.08975","name":"debug 29","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":780,"y":560,"wires":[]},{"id":"e901f0db6881d4b9","type":"function","z":"58b5e101.08975","name":"Group Status","func":" \nlet groupcnt = msg.payload.length -18   ;\nmsg.AC_Groups_Count = groupcnt/8;\nmsg.AC_Group = []\nfor (let i = 0; i < msg.AC_Groups_Count; i++) {\n  msg.AC_Group[i] = {}\n    \n  switch (msg.payload[16+(i*8)] & 240) {\n  case 0:\n    msg.AC_Group[i].PowerState = \"Off\"\n    break;\n  case 16:\n    msg.AC_Group[i].PowerState = \"On\"\n    break;\n  case 48:\n    msg.AC_Group[i].PowerState = \"Turbo\"\n    break;\n  case 64:\n    msg.AC_Group[i].PowerState = \"On - Currently Off\"\n    break;\n\n }\n msg.AC_Group[i].Zone = (msg.payload[16+(i*8)] & 15) + 1;\n msg.AC_Group[i].Open = msg.payload[17+(i*8)];\n}\n\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":590,"y":560,"wires":[["9c93168910c197ea"]]},{"id":"dd5d3c999050923b","type":"ha-sensor","z":"58b5e101.08975","name":"AirConditioner","entityConfig":"2e963d9ad1527967","version":0,"state":"AC[0].Status","stateType":"msg","attributes":[{"property":"UnitNumber","value":"AC[0].UnitNumber","valueType":"msg"},{"property":"Status","value":"AC[0].Status","valueType":"msg"},{"property":"Mode","value":"AC[0].Mode","valueType":"msg"},{"property":"FanSpeed","value":"AC[0].FanSpeed","valueType":"msg"},{"property":"SetPoint","value":"AC[0].SetPoint","valueType":"msg"},{"property":"Temp","value":"AC[0].Temp","valueType":"msg"}],"inputOverride":"allow","outputProperties":[],"x":580,"y":500,"wires":[["d83ac1da380d21ff"]]},{"id":"2e963d9ad1527967","type":"ha-entity-config","server":"dbbf171d.1ae948","deviceConfig":"53a0f31d1a3e0d77","name":"AirConditionerStatus","version":"6","entityType":"sensor","haConfig":[{"property":"name","value":"AirConditionerStatus"},{"property":"icon","value":""},{"property":"entity_picture","value":""},{"property":"entity_category","value":""},{"property":"device_class","value":""},{"property":"unit_of_measurement","value":""},{"property":"state_class","value":""}],"resend":false,"debugEnabled":false},{"id":"dbbf171d.1ae948","type":"server","name":"Home Assistant","addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"","connectionDelay":false,"cacheJson":false,"heartbeat":false,"heartbeatInterval":"","statusSeparator":"","enableGlobalContextStore":false},{"id":"53a0f31d1a3e0d77","type":"ha-device-config","name":"AirConditionerStatus_Config","hwVersion":"","manufacturer":"Node-RED","model":"","swVersion":""}]

**Comment by ctrl-freak** [comment]
Adding the sensor inside the Flow is a great idea, nice.

I'm offline, so don't have a chance to test this, but look forward to when I can.

I made good progress on the function to send commands, but hit a bug and didn't get back to finishing it off. I should probably commit it here anyway.

In the mean time, a Python HA custom component has been completed and tested:

https://github.com/nathanvdh/homeassistant-airtouch2plus

I'm using that, while it's not perfect (I haven't been able to diagnose the bugs I'm experiencing to report them) it's a more complete solution built on existing code for other AirTouch products.

I'm hoping to finish this flow off, at least as a personal milestone, just unsure when that'll happen.

**Comment by ctrl-freak** [comment]
Using the ha-sensor from node-red-contrib-home-assistant-websocket is an alternative to MQTT if you're not already running your own broker.

I can see your flow doesn't have code for the CRC16 check byte, which is required to send commands. Be sure to load up the flow in this repo, as I've done the heavy lifting there.
